# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d0ae643eff51d33dd0c885789faeb02f5e7cd41ddf6030cb4cb790e4742e5c643db90b512408f4f7e1ebc64bcf69e3f4bd17911a57c0c7382452aa6840f51cb

test:
  secret_key_base: f9fe18d3aa4dd4e3d8a418333d85dbf2ef06f98a921e24088e28f1072a90dd7bd957d37a065811b2fbe542debb4378f70b06c4d238719e35d3ded40086f2dad8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
